name: KICS Github Action
  uses: Checkmarx/kics-github-action@v1.6
  with:
    # path to file or directory to scan
    path: .
    # file path to store result in json format
    output_path: .
    # file path to store source internal representation in JSON format
    payload_path: # optional
    # path to directory with queries (default "./assets/queries")
    queries: # optional
    # verbose scan
    verbose: # optional
