name: KICS Github Action
on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Mkdir results-dir
      # make sure results dir is created
      run: mkdir -p results-dir
    - name: run kics Scan
      uses: Checkmarx/kics-github-action@v1.6
      with:
        path: .
        ##fail_on: high,medium
        output_path: results-dir
        run: cat results-dir/results.json

